Fix compile error in zstd_compression.cpp when using system ZStd (#15917)
When the system ZStd version of 1.38 or above is used,, a compiler warning is triggered due to calling a deprecated zstd function

```
[47/2376] Building CXX object Code/Framework/AzCore/CMakeFiles/AzCore.dir/profile/Unity/unity_2_cxx.cxx.o
FAILED: Code/Framework/AzCore/CMakeFiles/AzCore.dir/profile/Unity/unity_2_cxx.cxx.o
/usr/sbin/clang++ -DAZ_BUILD_CONFIGURATION_TYPE=\"profile\" -DAZ_ENABLE_DEBUG_TOOLS -DAZ_ENABLE_TRACING -DAZ_PROFILE_BUILD -DLINUX -DLINUX64 -DNDEBUG -D_FORTIFY_SOURCE=2 -D_HAS_EXCEPTIONS=0 -D_PROFILE -D__linux__ -DCMAKE_INTDIR=\"profile\" -I/home/lumberyard-employee-dm/o3de/Code/Framework/AzCore/. -I/home/lumberyard-employee-dm/o3de/Code/Framework/AzCore/Platform/Linux -I/home/lumberyard-employee-dm/o3de/Code/Framework/AzCore/Platform/Common -isystem /home/lumberyard-employee-dm/.o3de/3rdParty/packages/Lua-5.4.4-rev1-linux/Lua/include -isystem /home/lumberyard-employee-dm/.o3de/3rdParty/packages/RapidJSON-1.1.0-rev1-multiplatform/RapidJSON/include -isystem /home/lumberyard-employee-dm/.o3de/3rdParty/packages/RapidXML-1.13-rev1-multiplatform/RapidXML/include -isystem /home/lumberyard-employee-dm/.o3de/3rdParty/packages/zlib-1.2.11-rev5-linux/zlib/include -isystem /home/lumberyard-employee-dm/.o3de/3rdParty/packages/cityhash-1.1-multiplatform/cityhash/src -fno-exceptions -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Wno-inconsistent-missing-override -Wrange-loop-analysis -Wno-unknown-warning-option -Wno-parentheses -Wno-reorder -Wno-switch -Wno-undefined-var-template -msse4.1  -O2 -g -fstack-protector-all -fstack-check -std=c++17 -fPIC -MD -MT Code/Framework/AzCore/CMakeFiles/AzCore.dir/profile/Unity/unity_2_cxx.cxx.o -MF Code/Framework/AzCore/CMakeFiles/AzCore.dir/profile/Unity/unity_2_cxx.cxx.o.d -o Code/Framework/AzCore/CMakeFiles/AzCore.dir/profile/Unity/unity_2_cxx.cxx.o -c /home/lumberyard-employee-dm/o3de/build/linux/Code/Framework/AzCore/CMakeFiles/AzCore.dir/Unity/unity_2_cxx.cxx
In file included from /home/lumberyard-employee-dm/o3de/build/linux/Code/Framework/AzCore/CMakeFiles/AzCore.dir/Unity/unity_2_cxx.cxx:9:
/home/lumberyard-employee-dm/o3de/Code/Framework/AzCore/AzCore/Compression/zstd_compression.cpp:78:16: error: 'ZSTD_resetCStream' is deprecated: use ZSTD_CCtx_reset, see zstd.h for detailed instructions [-Werror,-Wdeprecated-declarations]
    size_t r = ZSTD_resetCStream(m_streamCompression,0);
               ^
/usr/include/zstd.h:2569:1: note: 'ZSTD_resetCStream' has been explicitly marked deprecated here
ZSTD_DEPRECATED("use ZSTD_CCtx_reset, see zstd.h for detailed instructions")
^
/usr/include/zstd.h:59:40: note: expanded from macro 'ZSTD_DEPRECATED'
                                       ^
In file included from /home/lumberyard-employee-dm/o3de/build/linux/Code/Framework/AzCore/CMakeFiles/AzCore.dir/Unity/unity_2_cxx.cxx:9:
/home/lumberyard-employee-dm/o3de/Code/Framework/AzCore/AzCore/Compression/zstd_compression.cpp:158:27: error: 'ZSTD_resetDStream' is deprecated: use ZSTD_DCtx_reset, see zstd.h for detailed instructions [-Werror,-Wdeprecated-declarations]
        m_nextBlockSize = ZSTD_resetDStream(m_streamDecompression);
                          ^
/usr/include/zstd.h:2638:1: note: 'ZSTD_resetDStream' has been explicitly marked deprecated here
ZSTD_DEPRECATED("use ZSTD_DCtx_reset, see zstd.h for detailed instructions")
^
/usr/include/zstd.h:59:40: note: expanded from macro 'ZSTD_DEPRECATED'
                                       ^
2 errors generated.
```

Signed-off-by: lumberyard-employee-dm <56135373+lumberyard-employee-dm@users.noreply.github.com>