Workaround VS2022 compiler issue in Debug configuration (#11221)
When builing the AnimGraphStateMachineInterruptionTests.cpp in debug
configuration using the MSVC v143 toolset, the `EXPECT_EQ` calls fail to
compile when both parameters are bools.

Instead of using EXPECT_EQ for the comparison of booleans, EXPECT_THAT
is used instead and that avoids the compiler issue.

Below is the compiler issue
```
1>------ Build started: Project: EMotionFX.Tests, Configuration: debug
x64 ------
1>AnimGraphStateMachineInterruptionTests.cpp
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(171,25):
error C2039: 'Compare': is not a member of 'testing::internal'
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(171,25):
error C2039:                         EXPECT_EQ(activeObjects.m_stateA,
compareAgainst.m_stateA)
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(171,25):
error C2039:                         ^
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : see declaration of 'testing::internal'
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : namespace internal {
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(173,25):
error C2039: 'Compare': is not a member of 'testing::internal'
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(173,25):
error C2039:                         EXPECT_EQ(activeObjects.m_stateB,
compareAgainst.m_stateB)
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(173,25):
error C2039:                         ^
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : see declaration of 'testing::internal'
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : namespace internal {
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(175,25):
error C2039: 'Compare': is not a member of 'testing::internal'
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(175,25):
error C2039:                         EXPECT_EQ(activeObjects.m_stateC,
compareAgainst.m_stateC)
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(175,25):
error C2039:                         ^
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : see declaration of 'testing::internal'
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : namespace internal {
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(177,25):
error C2039: 'Compare': is not a member of 'testing::internal'
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(177,25):
error C2039:
EXPECT_EQ(activeObjects.m_transitionLeft,
compareAgainst.m_transitionLeft)
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(177,25):
error C2039:                         ^
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : see declaration of 'testing::internal'
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : namespace internal {
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(179,25):
error C2039: 'Compare': is not a member of 'testing::internal'
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(179,25):
error C2039:
EXPECT_EQ(activeObjects.m_transitionMiddle,
compareAgainst.m_transitionMiddle)
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(179,25):
error C2039:                         ^
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : see declaration of 'testing::internal'
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : namespace internal {
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(181,25):
error C2039: 'Compare': is not a member of 'testing::internal'
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(181,25):
error C2039:
EXPECT_EQ(activeObjects.m_transitionRight,
compareAgainst.m_transitionRight)
1>D:\o3de\o3de\Gems\EMotionFX\Code\Tests\AnimGraphStateMachineInterruptionTests.cpp(181,25):
error C2039:                         ^
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : see declaration of 'testing::internal'
1>D:\3rdParty\packages\googletest-1.8.1-rev4-windows\googletest\include\gmock/gmock-more-actions.h(45):
message : namespace internal {
1>Done building project "EMotionFX.Tests.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped
==========
```

Signed-off-by: lumberyard-employee-dm <56135373+lumberyard-employee-dm@users.noreply.github.com>

Signed-off-by: lumberyard-employee-dm <56135373+lumberyard-employee-dm@users.noreply.github.com>