Fix GCC error being unable to resolve AZStd::construct_at for the EnvironmentHolder class caused by visibility of the constructor for AllocationManager and NameDictionary
Code/Framework/AzCore/AzCore/Name/NameDictionary.cpp:40:115:   required from here
Code/Framework/AzCore/./AzCore/Module/Environment.h:259:36: error: no matching function for call to ‘construct_at(AZ::NameDictionary*)’
259 |                 AZStd::construct_at(std::launder(reinterpret_cast<T*>(&m_value)), AZStd::forward<Args>(args)...);

Signed-off-by: Steve Pham <82231385+spham-amzn@users.noreply.github.com>