Fix undefined reference to symbols to symbols in ScenaData from NvCloth.Editor.Static module caused by an unnecessary include
o3de/build/linux_gcc/bin/profile/libNvCloth.Editor.Gem.so dbg MODULE_LIBRARY DETACH
    /usr/bin/ld: lib/profile/libNvCloth.Editor.Static.a(ClothRule.cpp.o):(.data.rel.ro._ZTVN2AZ8SceneAPI9SceneData22SceneNodeSelectionListE[_ZTVN2AZ8SceneAPI9SceneData22SceneNodeSelectionListE]+0x50): undefined reference to `AZ::SceneAPI::SceneData::SceneNodeSelectionList::GetSelectedNodeCount() const'
    /usr/bin/ld: lib/profile/libNvCloth.Editor.Static.a(ClothRule.cpp.o):(.data.rel.ro._ZTVN2AZ8SceneAPI9SceneData22SceneNodeSelectionListE[_ZTVN2AZ8SceneAPI9SceneData22SceneNodeSelectionListE]+0x58): undefined reference to `AZ::SceneAPI::SceneData::SceneNodeSelectionList::GetSelectedNode(unsigned long) const'
    /usr/bin/ld: lib/profile/libNvCloth.Editor.Static.a(ClothRule.cpp.o):(.data.rel.ro._ZTVN2AZ8SceneAPI9SceneData22SceneNodeSelectionListE[_ZTVN2AZ8SceneAPI9SceneData22SceneNodeSelectionListE]+0x60): undefined reference to `AZ::SceneAPI::SceneData::SceneNodeSelectionList::AddSelectedNode(AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::allocator> const&)'

Signed-off-by: Steve Pham <82231385+spham-amzn@users.noreply.github.com>