Fix for the Physx Editor Gem no declaring the required -fexceptions GCC flag
home/ANT.AMAZON.COM/spham/.o3de/3rdParty/packages/poly2tri-7f0487a-rev1-linux/poly2tri/poly2tri/include/poly2tri/common/shapes.h:141:56: error: exception handling disabled, use ‘-fexceptions’ to enable

Signed-off-by: Steve Pham <82231385+spham-amzn@users.noreply.github.com>