Fixes release only clang compiler error due to unused variable in xcb:
```
XcbNativeWindow.cpp:545:34: error: variable 'error' set but not used [-Werror,-Wunused-but-set-variable]
  545 |         if (xcb_generic_error_t* error = xcb_request_check(m_xcbConnection, cookie))
      |                                  ^
```

This is due to the AZ_Error macro being a no-op in release monolithic builds.

Signed-off-by: Nicholas Lawson <70027408+nick-l-o3de@users.noreply.github.com>