Remove AZ_Assert validating the src and dest pointers against nullptr because it breaks under GCC for constexpr from constructor calls:
Code/Framework/AzCore/./AzCore/std/string/fixed_string.inl:413:29:   in 'constexpr' expansion of 'AZStd::char_traits<char>::copy(data, ptr, count)'
Code/Framework/AzCore/./AzCore/std/string/string_view.h:419:28: error: '(((char*)(&<anonymous>.AZ::IO::BasicPath<AZStd::basic_fixed_string<char, 1024, AZStd::char_traits<char> > >::m_path.AZStd::basic_fixed_string<char, 1024, AZStd::char_traits<char> >::m_buffer)) == 0)' is not a constant expression
  419 |             AZ_Assert(dest != nullptr && src != nullptr, "Invalid input!");
      |                       ~~~~~^~~~~~~~~~

Signed-off-by: Steve Pham <82231385+spham-amzn@users.noreply.github.com>