Fixed error C4855: implicit capture of 'this' via '[=]' is deprecated in '/std:c++20'
Signed-off-by: Luis Sempé <58790905+lsemp3d@users.noreply.github.com>