Fix for the Whitebox Editor Gem no declaring the required -fexceptions GCC flag for the OpenMesh 3rd Party library
/3rdParty/packages/OpenMesh-8.1-rev3-linux/OpenMesh/include/OpenMesh/Core/IO/SR_binary_spec.hh:240:68: error: exception handling disabled, use ‘-fexceptions’ to enable
  240 |     throw std::runtime_error("Cannot store string longer than 64Kb");

Signed-off-by: Steve Pham <82231385+spham-amzn@users.noreply.github.com>