Fixes a compile error with assimp
assimp contains an expression that always evaluates to true,
which causes compiler error C4296.

O3DE auto enables this warning as well as warnings as errors,
and MSVC completely ignores the "Disable All Warnings" option
when it comes to specific warnings being enabled, so it has to be
added specifically to the compile options for assimp

Signed-off-by: Nicholas Lawson <70027408+nick-l-o3de@users.noreply.github.com>