VS2019 fix: Fixed ambigious call to the GetTemplateIdentity (#16992)
Because the `AZStd::span` class has a default template argument, Visual Studio
2019 compiler gets has a parsing bug between selecting the function
overload which accepts a "template template" parameter which is
templated on a type parameter followed by a non-type parameter `<class,
auto>` and the
overload which accepts a "template template" parameter argument which is
templated on a variadic argument list of type parameters `<class...>`

As the AZStd::span is a type parameter, followed by a non-type paraamter `<T, Extent=std::numeric_limits<size_t>::max()>`., the former overload should be the one that is selected.

```
17:44:41
   D:\workspace\o3de\Code\Framework\AzCore\AzCore/RTTI/TypeInfo.h(515,5):
   error C2668: 'AZ::AzGenericTypeInfo::Internal::GetTemplateIdentity':
   ambiguous call to overloaded function
   [D:\workspace\o3de\build\windows\Code\Framework\AzCore\O3DEKernel.vcxproj]
   17:44:41
      D:\workspace\o3de\Code\Framework\AzCore\AzCore/RTTI/TypeInfo.h(515,5):
      error C2668:
      AZ_TYPE_INFO_INTERNAL_SPECIALIZED_TEMPLATE_PREFIX_UUID(AZStd::span,
      "AZStd::span", "{2FCDBAB3-45E0-4159-A91D-FD1D37056C0F}",
      AZ_TYPE_INFO_INTERNAL_TYPENAME);
      [D:\workspace\o3de\build\windows\Code\Framework\AzCore\O3DEKernel.vcxproj]
```

Signed-off-by: lumberyard-employee-dm <56135373+lumberyard-employee-dm@users.noreply.github.com>