Fixes for Linux/GCC build errors (#11909)
* linux/gcc fix for the following errors:

n file included from /home/github/o3de/Code/Framework/AzCore/./AzCore/Serialization/SerializeContext.h:2619,
                 from /home/github/o3de/Code/Framework/AzCore/./AzCore/Component/EntityUtils.h:12,
                 from /home/github/o3de/Code/Framework/AzCore/AzCore/Component/EntityUtils.cpp:9:
/home/github/o3de/Code/Framework/AzCore/./AzCore/Serialization/AZStdContainers.inl: In instantiation of ‘bool AZ::Internal::AZStdBasicContainer<T, IsStableIterators>::RemoveElement(void*, const void*, AZ::SerializeContext*) [with T = AZStd::vector<AZ::Entity*>; bool IsStableIterators = false]’:
/home/github/o3de/Code/Framework/AzCore/./AzCore/Serialization/AZStdContainers.inl:294:21:   required from here
/home/github/o3de/Code/Framework/AzCore/./AzCore/Serialization/AZStdContainers.inl:299:38: error: variable ‘prevIter’ set but not used [-Werror=unused-but-set-variable]
  299 |                 typename T::iterator prevIter{};
      |                                      ^~~~~~~~
cc1plus: all warnings being treated as errors

/home/github/o3de/Code/Framework/AzCore/Tests/Serialization.cpp: In instantiation of ‘void UnitTest::gtest_case_GenericsLoadInPlaceFixture_::ClearsOnLoadInPlace<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = AZStd::vector<int>]’:
/home/github/o3de/Code/Framework/AzCore/Tests/Serialization.cpp:7802:5:   required from here
/home/github/o3de/Code/Framework/AzCore/Tests/Serialization.cpp:7808:38: error: variable ‘insertIter’ set but not used [-Werror=unused-but-set-variable]
 7808 |         typename TypeParam::iterator insertIter{};
      |                                      ^~~~~~~~~~
cc1plus: all warnings being treated as errors

/home/github/o3de/Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/ClientTransceiver.cpp: In member function ‘virtual AzFramework::RemoteToolsEndpointInfo ScriptCanvas::Debugger::ClientTransceiver::GetNetworkTarget()’:
/home/github/o3de/Gems/ScriptCanvas/Code/Include/ScriptCanvas/Debugger/ClientTransceiver.cpp:171:44: error: unused variable ‘remoteTools’ [-Werror=unused-variable]
  171 |             if (AzFramework::IRemoteTools* remoteTools = RemoteToolsInterface::Get())
      |                                            ^~~~~~~~~~~
cc1plus: all warnings being treated as errors

/home/github/.o3de/3rdParty/packages/openimageio-opencolorio-2.3.17-rev2-linux/OpenImageIO/include/OpenImageIO/string_view.h: In member function ‘constexpr const charT& OpenImageIO_v2_3::string_view::at(std::size_t) const’:
/home/github/.o3de/3rdParty/packages/openimageio-opencolorio-2.3.17-rev2-linux/OpenImageIO/include/OpenImageIO/string_view.h:165:68: error: exception handling disabled, use ‘-fexceptions’ to enable
  165 |             throw(std::out_of_range("OpenImageIO::string_view::at"));
      |                                                                    ^

Signed-off-by: Steve Pham <82231385+spham-amzn@users.noreply.github.com>

* Fix undefined reference to symbols to symbols in ScenaData from NvCloth.Editor.Static module caused by an unnecessary include

o3de/build/linux_gcc/bin/profile/libNvCloth.Editor.Gem.so dbg MODULE_LIBRARY DETACH
    /usr/bin/ld: lib/profile/libNvCloth.Editor.Static.a(ClothRule.cpp.o):(.data.rel.ro._ZTVN2AZ8SceneAPI9SceneData22SceneNodeSelectionListE[_ZTVN2AZ8SceneAPI9SceneData22SceneNodeSelectionListE]+0x50): undefined reference to `AZ::SceneAPI::SceneData::SceneNodeSelectionList::GetSelectedNodeCount() const'
    /usr/bin/ld: lib/profile/libNvCloth.Editor.Static.a(ClothRule.cpp.o):(.data.rel.ro._ZTVN2AZ8SceneAPI9SceneData22SceneNodeSelectionListE[_ZTVN2AZ8SceneAPI9SceneData22SceneNodeSelectionListE]+0x58): undefined reference to `AZ::SceneAPI::SceneData::SceneNodeSelectionList::GetSelectedNode(unsigned long) const'
    /usr/bin/ld: lib/profile/libNvCloth.Editor.Static.a(ClothRule.cpp.o):(.data.rel.ro._ZTVN2AZ8SceneAPI9SceneData22SceneNodeSelectionListE[_ZTVN2AZ8SceneAPI9SceneData22SceneNodeSelectionListE]+0x60): undefined reference to `AZ::SceneAPI::SceneData::SceneNodeSelectionList::AddSelectedNode(AZStd::basic_string<char, AZStd::char_traits<char>, AZStd::allocator> const&)'

Signed-off-by: Steve Pham <82231385+spham-amzn@users.noreply.github.com>