Clang build fix removed unused `proxyAddress` variable.
The variable is causing a set, but not used warning when building with clang

```
o3de/Code/Framework/AzToolsFramework/./AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h:396:31: error: variable 'proxyAddress' set but not used [-Werror,-Wunused-but-set-variable]
                        void* proxyAddress{};
```

Signed-off-by: lumberyard-employee-dm <56135373+lumberyard-employee-dm@users.noreply.github.com>