Fixes a linux clang-15 compile error
```XConsole.cpp:809:10: error: 'this' pointer cannot be null in
well-defined C++ code; pointer may be assumed to always convert to true
[-Werror,-Wundefined-bool-conversion]```

Signed-off-by: Nicholas Lawson <70027408+nick-l-o3de@users.noreply.github.com>