Make sure -fexceptions is also enabled for EditorPythonBindings.Editor tests due to exceptions needed for pybind:
/3rdParty/packages/pybind11-2.4.3-rev2-multiplatform/pybind11/include/pybind11/detail/common.h:680:111: error: exception handling disabled, use ‘-fexceptions’ to enable
  680 | [[noreturn]] PYBIND11_NOINLINE inline void pybind11_fail(const char *reason) { throw std::runtime_error(reason); }

Signed-off-by: Steve Pham <82231385+spham-amzn@users.noreply.github.com>